INSERT INTO tb_user (name, email, password) VALUES ('Alex Brown', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Drama');
INSERT INTO tb_genre (name) VALUES ('Aventura');
INSERT INTO tb_genre (name) VALUES ('Açâo');

INSERT INTO tb_movie (genre_id, title, sub_Title, year, img_Uri, synopsis) VALUES (1, 'Coringa', 'Coloque um sorriso nessa cara.', 2019, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/rNqVp7C3ajnxxe6n2151mG8Ttck.jpg','Arthur Fleck trabalha como palhaço para uma agência de talentos e, toda semana, precisa comparecer a uma agente social, devido aos seus conhecidos problemas mentais. Após ser demitido, Fleck reage mal à gozação de três homens em pleno metrô e os mata. Os assassinatos iniciam um movimento popular contra a elite de Gotham City, da qual Thomas Wayne é seu maior representante.');            
INSERT INTO tb_movie (genre_id, title, sub_Title, year, img_Uri, synopsis) VALUES (3, 'The Silencing', 'The silencing.', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/lviaLi9G9SAeRnp0H8LJubEVTAS.jpg','Um caçador aposentado vive isolado em um santuário de vida selvagem se envolve em um jogo mortal de gato e rato quando ele e o xerife local partem para rastrear um assassino cruel que pode ter sequestrado sua filha anos atrás.');              
INSERT INTO tb_movie (genre_id, title, sub_Title, year, img_Uri, synopsis) VALUES (3, 'Batman: O Cavaleiro das Trevas', 'Por que está tão sério?', 2008, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/lHhZrxYk8pi25UYKgHVJSbGCwI9.jpg','Após dois anos desde o surgimento do Batman, os criminosos de Gotham City têm muito o que temer. Com a ajuda do tenente James Gordon e do promotor público Harvey Dent, Batman luta contra o crime organizado. Acuados com o combate, os chefes do crime aceitam a proposta feita pelo Coringa e o contratam para combater o Homem-Morcego.');      
INSERT INTO tb_movie (genre_id, title, sub_Title, year, img_Uri, synopsis) VALUES (1, 'O Pianista', 'Music was his passion. Survival was his masterpiece.', 2002, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/fuFcyX9pXcLeKfsEpArtnqV3gyX.jpg','Um pianista judeu polonês vê Varsóvia mudar gradualmente à medida que a Segunda Guerra Mundial começa. Szpilman é forçado a ir para o Gueto de Varsóvia, mas depois é separado de sua família durante a Operação Reinhard. A partir deste momento até que os prisioneiros dos campos de concentração sejam liberados, Szpilman se esconde em vários locais entre as ruínas de Varsóvia.');             
INSERT INTO tb_movie (genre_id, title, sub_Title, year, img_Uri, synopsis) VALUES (2, 'Vingadores: Ultimato', 'O fim de uma era!', 2019, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg','Após os eventos devastadores de "Vingadores: Guerra Infinita", o universo está em ruínas devido aos esforços do Titã Louco, Thanos. Com a ajuda de aliados remanescentes, os Vingadores devem se reunir mais uma vez a fim de desfazer as ações de Thanos e restaurar a ordem no universo de uma vez por todas, não importando as consequências.');             
INSERT INTO tb_movie (genre_id, title, sub_Title, year, img_Uri, synopsis) VALUES (2, 'Interestelar', 'O fim da terra não será o nosso fim.', 2014, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/xJHokMbljvjADYdit5fK5VQsXEG.jpg','As reservas naturais da Terra estão chegando ao fim e um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, possibilitando a continuação da espécie. Cooper é chamado para liderar o grupo e aceita a missão sabendo que pode nunca mais ver os filhos. Ao lado de Brand, Jenkins e Doyle, ele seguirá em busca de um novo lar.');             
INSERT INTO tb_movie (genre_id, title, sub_Title, year, img_Uri, synopsis) VALUES (1, 'O Jogo da Imitação', 'O verdadeiro enigma estava no homem que desvendou o código.', 2014, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/sixfWYfNegaGGHKdXrNNUHaMiAC.jpg','Em 1939, a recém-criada agência de inteligência britânica MI6 recruta Alan Turing, um aluno da Universidade de Cambridge, para entender códigos nazistas, incluindo o "Enigma", que criptógrafos acreditavam ser inquebrável. A equipe de Turing, incluindo Joan Clarke, analisa as mensagens de "Enigma", enquanto ele constrói uma máquina para decifrá-las.');             
INSERT INTO tb_movie (genre_id, title, sub_Title, year, img_Uri, synopsis) VALUES (1, 'O Poderoso Chefão', 'Uma oferta que você não vai poder recusar.', 1972, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/41xIKcLiM5ryfz4C9sZFcBOJGsK.jpg','Uma família mafiosa luta para estabelecer sua supremacia nos Estados Unidos depois da Segunda Guerra Mundial. Uma tentativa de assassinato deixa o chefão Vito Corleone incapacitado e força os filhos Michael e Sonny a assumir os negócios.');             
INSERT INTO tb_movie (genre_id, title, sub_Title, year, img_Uri, synopsis) VALUES (3, 'Matrix', 'Todos acham que é real.', 1999, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/oeZzovVxhgqdTWgiAB1huZbjRHf.jpg','Um jovem programador é atormentado por estranhos pesadelos nos quais sempre está conectado por cabos a um imenso sistema de computadores do futuro. À medida que o sonho se repete, ele começa a levantar dúvidas sobre a realidade. E quando encontra os misteriosos Morpheus e Trinity, ele descobre que é vítima do Matrix, um sistema inteligente e artificial que manipula a mente das pessoas e cria a ilusão de um mundo real enquanto usa os cérebros e corpos dos indivíduos para produzir energia.');           
INSERT INTO tb_movie (genre_id, title, sub_Title, year, img_Uri, synopsis) VALUES (2, 'O Senhor dos Anéis: O Retorno do Rei', 'O olho do inimigo está se movendo.', 2003, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg','O confronto final entre as forças do bem e do mal que lutam pelo controle do futuro da Terra Média se aproxima. Sauron planeja um grande ataque a Minas Tirith, capital de Gondor, o que faz com que Gandalf e Pippin partam para o local na intenção de ajudar a resistência. Um exército é reunido por Theoden em Rohan, em mais uma tentativa de deter as forças de Sauron. Enquanto isso, Frodo, Sam e Gollum seguem sua viagem rumo à Montanha da Perdição para destruir o anel.');                           